packages:
  - "*/src"
  # FIXME: Monaco Editor dependency issue
  # https://github.com/naitokosuke/slides/issues/12
  - "!2025-10-25/src"

catalog:
  # Slidev
  "@slidev/cli": ^52.10.0
  "@slidev/client": ^52.10.0
  "@slidev/theme-default": latest
  "@slidev/theme-seriph": latest

  # Vue
  vue: ^3.5.25
  "@vueuse/integrations": ^13.9.0

  # Iconify
  "@iconify-json/carbon": ^1.2.1
  "@iconify-json/devicon": ^1.2.25
  "@iconify-json/healthicons": ^1.1.21
  "@iconify-json/logos": ^1.2.10
  "@iconify-json/material-icon-theme": ^1.2.29
  "@iconify-json/mdi": ^1.2.3
  "@iconify-json/noto": ^1.2.7
  "@iconify-json/openmoji": ^1.2.0
  "@iconify-json/simple-icons": ^1.2.4
  "@iconify-json/skill-icons": ^1.2.0
  "@iconify-json/twemoji": ^1.1.15
  "@iconify-json/uim": ^1.1.9
  "@iconify/json": ^2.2.226

  # QR Code
  qrcode: ^1.5.4
