minimumReleaseAge: 1440

packages:
  - "*/src"
  # FIXME: Monaco Editor dependency issue
  # https://github.com/naitokosuke/slides/issues/12
  - "!2025-10-25/src"

catalogs:
  slidev:
    "@slidev/cli": ^52.10.0
    "@slidev/client": ^52.10.0
    "@slidev/theme-default": latest
    "@slidev/theme-seriph": latest
    vue: ^3.5.25
    vue-router: ^4.4.0
    vue-tsc: ^2.0.26
    "@vueuse/integrations": ^13.9.0
    prettier-plugin-slidev: ^1.0.5
    unocss: ^0.61.3
    markdown-it-magic-link: ^0.1.4
    playwright-chromium: ^1.45.1

  iconify:
    "@iconify-json/carbon": ^1.2.1
    "@iconify-json/devicon": ^1.2.25
    "@iconify-json/healthicons": ^1.1.21
    "@iconify-json/logos": ^1.2.10
    "@iconify-json/material-icon-theme": ^1.2.29
    "@iconify-json/mdi": ^1.2.3
    "@iconify-json/noto": ^1.2.7
    "@iconify-json/openmoji": ^1.2.0
    "@iconify-json/simple-icons": ^1.2.4
    "@iconify-json/skill-icons": ^1.2.0
    "@iconify-json/twemoji": ^1.1.15
    "@iconify-json/uim": ^1.1.9
    "@iconify/json": ^2.2.226

  lint:
    "@antfu/eslint-config": ^2.22.0
    "@eslint/config-inspector": ^0.5.1
    eslint: ^9.17.0
    eslint-plugin-format: ^0.1.3

  script:
    gunshi: ^0.27.5
    "@gunshi/docs": 0.27.5
